version: "3.8"

services:
  db:
    image: 'postgres:13.1-alpine'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres


  app:
    depends_on:
      - db
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

volumes:
  db: